import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {startServer} from './serve.mjs';
import {textContrast} from './contrast.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'review');await fs.mkdir(out,{recursive:true});
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const server=process.env.TEDUSTORE_REVIEW_URL?null:await startServer(0),url=(process.env.TEDUSTORE_REVIEW_URL||'http://127.0.0.1:'+server.address().port).replace(/\/$/,''),report={url,errors:[],requests:[],layouts:[],checks:{}};
const browser=await chromium.launch({headless:true,...(process.env.TEDUSTORE_CHROMIUM?{executablePath:process.env.TEDUSTORE_CHROMIUM}:{})});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'en-US'}),page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD'].includes(r.method())||!r.url().startsWith(url))report.requests.push({method:r.method(),url:r.url()});});
 await page.goto(url);await page.waitForSelector('.product-card');await page.evaluate(async()=>{await document.fonts.ready;for(const i of document.images)i.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});await page.waitForTimeout(1400);
 for(const [w,h]of [[1440,1000],[1024,900],[768,1024],[390,844],[360,800],[320,740]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(450);report.layouts.push(await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,missingImages:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).length,headerOverflow:document.querySelector('.header-inner').scrollWidth>document.querySelector('.header-inner').clientWidth})));await page.screenshot({path:path.join(out,`home-${w}.png`)});}
 await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(out,'desktop-full.png'),fullPage:true});
 assert.equal(await page.locator('.product-card').count(),6);report.checks.catalogue=6;
 await page.locator('[data-filter="carry"]').click();assert.equal(await page.locator('.product-card').count(),2);report.checks.categoryFilter=true;
 await page.locator('[data-filter="all"]').click();await page.selectOption('#sort','low');assert.equal(await page.locator('.product-card').first().locator('[data-product]').first().getAttribute('data-product'),'mug');report.checks.priceSort=true;
 await page.locator('[data-save="hoodie"]').click();await page.locator('[data-filter="saved"]').click();assert.equal(await page.locator('.product-card').count(),1);report.checks.saved=true;
 await page.locator('[data-filter="all"]').click();await page.locator('.product-card [data-product="hoodie"]').first().click();await page.locator('#add-to-bag').click();assert(await page.locator('#size-error').textContent());report.checks.sizeRequired=true;
 await page.locator('[data-size="M"]').click();await page.screenshot({path:path.join(out,'desktop-product.png')});await page.locator('#add-to-bag').click();assert.equal(await page.locator('#bag-count').textContent(),'1');
 await page.locator('[data-qty="0"][data-change="1"]').click();assert.equal(await page.locator('#bag-count').textContent(),'2');report.checks.quantity=true;
 await page.locator('#coupon-input').fill('WRONG');await page.locator('#apply-coupon').click();assert((await page.locator('#coupon-status').textContent()).includes('TEDU10'));await page.locator('#coupon-input').fill('TEDU10');await page.locator('#apply-coupon').click();assert((await page.locator('#coupon-status').textContent()).includes('10%'));report.checks.discount=true;
 await page.screenshot({path:path.join(out,'desktop-bag.png')});await page.keyboard.press('Escape');await page.reload();await page.waitForSelector('.product-card');assert.equal(await page.locator('#bag-count').textContent(),'2');report.checks.persistence=true;
 await page.locator('.header-actions [data-open="search-dialog"]').click();await page.locator('#search-input').fill('tote');assert.equal(await page.locator('.search-result').count(),1);await page.locator('#search-input').fill('no-such-piece');assert.equal(await page.locator('.search-result').count(),0);report.checks.searchAndEmpty=true;await page.keyboard.press('Escape');
 await page.locator('.header-actions [data-open="bag-dialog"]').click();await page.locator('#begin-checkout').click();await page.locator('#checkout-form button[type=submit]').click();assert(await page.locator('#checkout-error').textContent());report.checks.formValidation=true;
 await page.locator('#demo-details').click();await page.locator('input[name="delivery"][value="shipping"]').check();assert((await page.locator('#checkout-totals').textContent()).includes('79'));await page.screenshot({path:path.join(out,'desktop-checkout-details.png')});await page.locator('#checkout-form button[type=submit]').click();await page.locator('#simulate-checkout').click();assert(await page.locator('#checkout-error').textContent());report.checks.demoAcknowledgment=true;
 assert.equal(await page.locator('#checkout-content input[type=text],#checkout-content input[type=email]').count(),0);report.checks.noCardInputs=true;await page.locator('#demo-ack').check();await page.screenshot({path:path.join(out,'desktop-demo-payment.png')});await page.locator('#simulate-checkout').click();await page.waitForSelector('.receipt');assert((await page.locator('.receipt').textContent()).includes('No payment was made'));assert.equal(await page.locator('#bag-count').textContent(),'0');report.checks.simulatedReceipt=true;await page.screenshot({path:path.join(out,'desktop-receipt.png')});
 await page.locator('[data-open-payout]').click();assert((await page.locator('#payout-content').textContent()).includes('Not transferred'));report.checks.payout=true;await page.screenshot({path:path.join(out,'desktop-payout.png')});await page.locator('#clear-receipt').click();assert((await page.locator('#payout-content').textContent()).includes('Example basket'));report.checks.payoutReset=true;await page.keyboard.press('Escape');
 await page.locator('#language').click();assert.equal(await page.locator('html').getAttribute('lang'),'tr');await page.locator('.product-card [data-product="mug"]').first().click();assert((await page.locator('#product-title').textContent()).includes('Kupası'));report.checks.turkish=true;await page.keyboard.press('Escape');await page.locator('#language').click();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(out,'mobile-full.png'),fullPage:true});await page.locator('.mobile-menu').click();await page.screenshot({path:path.join(out,'mobile-menu.png')});await page.keyboard.press('Escape');
 await page.locator('.product-card [data-product="tee"]').first().click();await page.locator('[data-size="L"]').click();await page.screenshot({path:path.join(out,'mobile-product.png')});await page.locator('#add-to-bag').click();await page.locator('#begin-checkout').click();await page.locator('#demo-details').click();await page.locator('#checkout-form button[type=submit]').click();await page.locator('#demo-ack').check();await page.screenshot({path:path.join(out,'mobile-payment.png')});assert(await page.locator('#simulate-checkout').isVisible());report.checks.mobileCheckout=true;await page.keyboard.press('Escape');assert.equal(await page.locator('#checkout-content').textContent(),'');report.checks.contactCleared=true;
 await page.locator('.header-actions [data-open="bag-dialog"]').click();await page.locator('[data-remove="0"]').click();assert(await page.locator('.bag-empty').count());report.checks.removeAndEmptyBag=true;await page.keyboard.press('Escape');
 await page.locator('[data-filter="saved"]').click();await page.locator('[data-save="hoodie"]').click();assert(await page.locator('.empty-state').count());await page.locator('.empty-state [data-category="all"]').click();report.checks.emptySaved=true;
 await page.locator('.product-card [data-product="tee"]').first().click();await page.locator('[data-open="size-dialog"]').click();assert(await page.locator('#size-dialog').isVisible());await page.keyboard.press('Escape');assert(await page.locator('#product-dialog').isVisible());await page.keyboard.press('Escape');report.checks.layeredDialogs=true;
 await page.locator('[data-open="privacy-dialog"]').first().click();assert(await page.locator('#privacy-dialog').isVisible());await page.keyboard.press('Escape');report.checks.privacy=true;
 await page.locator('.faq summary').first().click();assert(await page.locator('.faq details').first().getAttribute('open')!==null);report.checks.faq=true;
 await page.locator('#sort').selectOption('high');assert.equal(await page.locator('.product-card').first().locator('[data-product]').first().getAttribute('data-product'),'hoodie');await page.locator('#sort').selectOption('az');report.checks.additionalSorts=true;
 await page.setViewportSize({width:1440,height:1000});report.contrast=await textContrast(page);assert.equal(report.contrast.issues.length,0);
 assert.equal(report.errors.length,0);assert.equal(report.requests.length,0);assert(report.layouts.every(l=>l.width===l.documentWidth&&l.missingImages===0&&!l.headerOverflow));
 await context.close();
}finally{await browser.close();if(server)await new Promise(resolve=>server.close(resolve));await fs.writeFile(path.join(out,'review.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
